sudo: false
language: python
python:
  - '3.8'
dist: bionic
cache:
  directories:
    - $HOME/.cache/pip
install:
  - pip3 install --upgrade pip "poetry>=1.0.10"
script:
  - poetry install
  - make -C docsource/ html
  - touch docsource/build/html/.nojekyll
deploy:
  - provider: pages
    verbose: true
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    local_dir: ./docsource/build/html
    keep_history: true
    on:
      branch: master
